In [10]:
# !jupyter nbextension enable – py widgetsnbextension – sys-prefix
# !jupyter serverextension enable voila – sys-prefix

In [13]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/adiun/Github/ML_Mini_Project/lung_cancer/lung_cancer_examples.csv")

In [15]:
df

           Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0          John         Wick   35       3      5       4       1
1          John  Constantine   27      20      2       5       1
2        Camela     Anderson   30       0      5       2       0
3          Alex       Telles   28       0      8       1       0
4         Diego     Maradona   68       4      5       6       1
5     Cristiano      Ronaldo   34       0     10       0       0
6        Mihail          Tal   58      15     10       0       0
7         Kathy        Bates   22      12      5       2       0
8        Nicole       Kidman   45       2      6       0       0
9           Ray      Milland   52      18      4       5       1
10      Fredric        March   33       4      8       0       0
11          Yul      Brynner   18      10      6       3       0
12         Joan     Crawford   25       2      5       1       0
13         Jane        Wyman   28      20      2       8       1
14         Anna      Magnani   34      25      4       8       1
15   Katharine       Hepburn   39      18      8       1       0
16   Katharine       Hepburn   42      22      3       5       1
17       Barbra    Streisand   19      12      8       0       0
18      Maggie         Smith   62       5      4       3       1
19      Glenda       Jackson   73      10      7       6       1
20        Jane         Fonda   55      15      1       3       1
21  Maximilian        Schell   33       8      8       1       0
22     Gregory          Peck   22      20      6       2       0
23      Sidney       Poitier   44       5      8       1       0
24         Rex      Harrison   77       3      2       6       1
25         Lee        Marvin   21      20      5       3       0
26        Paul      Scofield   37      15      6       2       0
27         Rod       Steiger   34      12      8       0       0
28        John         Wayne   55      20      1       4       1
29        Gene       Hackman   40      20      2       7       1
30      Marlon        Brando   36      13      5       2       0
31        Jack        Lemmon   56      20      3       3       1
32        Jack     Nicholson   47      15      1       8       1
33       Peter        Finch    62      25      3       4       1
34     Richard      Dreyfuss   26      10      7       2       0
35      Dustin       Hoffman   25      20      8       2       0
36       Henry        Henry    59      20      3       4       1
37      Robert        Duvall   62      15      5       5       1
38       Ellen       Burstyn   33      25      8       2       0
39        Faye       Dunaway   37      10      5       3       0
40       Diane        Keaton   50      20      2       4       1
41        Jane         Fonda   47      12      8       0       0
42       Sally         Field   69      20      5       4       1
43       Sissy        Spacek   63      20      4       5       1
44     Jessica         Lange   39      15      7       2       0
45     Gwyneth       Paltrow   21      20      8       3       0
46       Halle         Berry   31      20      9       4       0
47      Nicole        Kidman   28      10      4       1       0
48    Charlize        Theron   53      20      6       3       1
49   Katharine       Hepburn   62      20      5       6       1
50   Katharine       Hepburn   42      12      6       2       0
51      Barbra     Streisand   44      30      1       6       1
52      Maggie         Smith   26      34      1       8       1
53      Glenda       Jackson   35      20      5       1       0
54      Ernest      Borgnine   26      13      6       1       0
55        Alec      Guinness   77      20      5       4       1
56    Charlton        Heston   75      15      3       5       1
57     Gregory          Peck   43      30      3       8       1
58      Sidney       Poitier   51      25      9       0       0

In [14]:
# Linear regression

from sklearn import linear_model

In [17]:
reg = linear_model.LinearRegression()
reg.fit(df[['Age','Smokes','AreaQ','Alkhol']], df.Result)

LinearRegression()

In [18]:
reg.coef_

array([ 0.01277977,  0.00216894, -0.06267237,  0.0939671 ])

In [19]:
reg.intercept_

-0.08095940164327492

In [21]:
target = reg.predict([[20,1,25,50]])
print(target)

[3.30835078]

C:\Users\adiun\Github\ML_Mini_Project\ml_venv\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(